/* Perform Business Activities */

SELECT * FROM employee_data;

SELECT  DEPARTMENT, COUNT(DESIGNATION) DESIGNATION
FROM employee_data
WHERE GENDER = "MALE"
GROUP BY DEPARTMENT
ORDER BY DESIGNATION DESC;

